### PR TITLE
pbench-copy-sosreports: fix the wrong state transition name

### LINKED ISSUE #907: pbench-copy-sosreports contains wrong state transition for linkdest variable.
The pbench-copy-sosreports script is scanning the `TO-COPY-SOS` state directory to get the symlinks for which it needs to copy the sos report. But after copying is done, it is moving the symlinks to `TO-INDEX` state directory that is wrong. The variable `linkdest` needs to be changed for that.

It doesn't have any proper state directory also, for moving results, after copying sos reports. It supposed to have some state directory called `COPIED-SOS` for moving.

### PR DESCRIPTION
**Pull request by tenstormavi**
Fixes #907 

This PR will add the missing state transition for copy-sos-reports
i.e `COPIED-SOS`. 

It will also remove the `DONE` state transition because it is not being used by any server scripts, not anymore. There was a duplicate `TO-UNPACK` state transition name, that is also removed now.

### CODE REVIEW

File: server/pbench/bin/pbench-base.sh [hunk 1]
```diff
@@ -78,7 +78,7 @@ export mail_recipients=$(getconf.py mailto pbench-server)
 # make all the state directories for the pipeline and any others needed
 LINKDIRS="TODO TO-UNPACK TO-COPY-SOS TO-SYNC SYNCED TO-LINK TO-INDEX TO-BACKUP \
 	INDEXED WONT-INDEX DONE BAD-MD5 SATELLITE-MD5-PASSED SATELLITE-MD5-FAILED \
-	TO-DELETE SATELLITE-DONE TO-UNPACK UNPACKED MOVED-UNPACKED"
+	TO-DELETE SATELLITE-DONE TO-UNPACK UNPACKED MOVED-UNPACKED COPIED-SOS"
```
Comment (ndokos) [inline server/pbench/bin/pbench-base.sh]: Can you reorder these, so that they are paired properly? Just  put the related states together (e.g. TO-INDEX INDEXED WONT-INDEX). Put any general final states (e.g. BAD_MD5) at the end on their own line and add a comment to indicate that they are final states.

**Comment by tenstormavi** [comment]
@ndokos updated the PR as requested. PTAL.

File: server/pbench/bin/pbench-base.sh [hunk 2]
```diff
@@ -76,9 +76,17 @@ fi
...
+# final state at the end
+LINKDIRS="TODO BAD-MD5 \
+    TO-UNPACK UNPACKED MOVED-UNPACKED  \
+    TO-SYNC SYNCED \
+    TO-LINK \
+    TO-INDEX INDEXED WONT-INDEX \
+    TO-COPY-SOS COPIED-SOS \
+    TO-BACKUP \
+    SATELLITE-MD5-PASSED SATELLITE-MD5-FAILED \
+    TO-DELETE SATELLITE-DONE"
```
Comment (portante) [inline server/pbench/bin/pbench-base.sh]: I performed the following to compare the two:
```
$ LINKDIRS="TODO TO-UNPACK TO-COPY-SOS TO-SYNC SYNCED TO-LINK TO-INDEX TO-BACKUP \
INDEXED WONT-INDEX DONE BAD-MD5 SATELLITE-MD5-PASSED SATELLITE-MD5-FAILED \
TO-DELETE SATELLITE-DONE TO-UNPACK UNPACKED MOVED-UNPACKED"
$ for i in $LINKDIRS ; do echo $i; done | sort > orig.linkdirs.lis
$ LINKDIRS="TODO BAD-MD5 \
     TO-UNPACK UNPACKED MOVED-UNPACKED  \
     TO-SYNC SYNCED \
     TO-LINK \
     TO-INDEX INDEXED WONT-INDEX \
     TO-COPY-SOS COPIED-SOS \
     TO-BACKUP \
     SATELLITE-MD5-PASSED SATELLITE-MD5-FAILED \
     TO-DELETE SATELLITE-DONE"
$ for i in $LINKDIRS ; do echo $i; done | sort > new.linkdirs.lis
$ diff -c orig.linkdirs.lis new.linkdirs.lis
*** orig.linkdirs.lis   2018-09-07 10:01:40.333072583 +0000
--- new.linkdirs.lis    2018-09-07 10:02:13.168546389 +0000
***************
*** 1,5 ****
  BAD-MD5
! DONE
  INDEXED
  MOVED-UNPACKED
  SATELLITE-DONE
--- 1,5 ----
  BAD-MD5
! COPIED-SOS
  INDEXED
  MOVED-UNPACKED
  SATELLITE-DONE
***************
*** 14,19 ****
  TO-LINK
  TO-SYNC
  TO-UNPACK
- TO-UNPACK
  UNPACKED
  WONT-INDEX
--- 14,18 ----
```

It looks like we added `COPIED-SOS`, but removed `DONE`, and removed the duplicate `TO-UNPACK`.

Do we still need the `DONE` state?

Comment (tenstormavi) [reply server/pbench/bin/pbench-base.sh]: @portante `DONE` is not being used by any of the server scripts, not anymore. That's why I removed it.

Comment (portante) [reply server/pbench/bin/pbench-base.sh]: @tenstormavi, great, can you be sure that is added to the commit comment?

**Comment by tenstormavi** [comment]
@portante @ndokos Rebased with master and Updated as requested. PTAL

**Comment by portante** [comment]
@tenstormavi, please rebase as soon as you can.

**Comment by tenstormavi** [comment]
@portante @ndokos rebased.
