### PR TITLE
Fix index names generated by pbench-report-status

### LINKED ISSUE #901: The pbench-report-status script appears to be using bad index names
Example index names failing to be created:

```
dsa.pbench.pbench-move-unpacked.2018-08-28T15:04:02
dsa.pbench.pbench-index.2018-08-28T15:05:02
dsa.pbench.pbench-server-prep-shim-002.2018-08-28T15:05:02
dsa.pbench.pbench-server-prep-shim-001.2018-08-28T15:05:02
```

The error message given is complaining about the capital "T" in the time string it seems:

```
[2018-08-28 09:35:03,252][DEBUG       ][action.admin.indices.create] [belichick-perf44] [dsa.pbench.pbench-index.2018-08-28T15:05:02] failed to create
org.elasticsearch.indices.InvalidIndexNameException: [dsa.pbench.pbench-index.2018-08-28T15:05:02] Invalid index name [dsa.pbench.pbench-index.2018-08-28T15:05:02], must be lowercase
```

The index names should be:
```
dsa.pbench.pbench-move-unpacked.2018-08-28
dsa.pbench.pbench-index.2018-08-28
dsa.pbench.pbench-server-prep-shim-002.2018-08-28
dsa.pbench.pbench-server-prep-shim-001.2018-08-28
```

### PR DESCRIPTION
**Pull request by ndokos**
Fixes #901.
 
 Index names are generated from the timestamp by dropping everything
 except the YYYY-MM-DD spec. In particular the capital T that separates
 the date from the time in the timestamp is not a legal character for
 an ES index name.
 
 Force UTC in pbench-base.sh: although servers are on UTC, laptops and
 test machines are not necessarily. Forcing UTC when running any server
 cripts simplified unit testing.

### CODE REVIEW

File: server/pbench/bin/pbench-report-status [hunk 1]
```diff
@@ -36,6 +40,16 @@ while true; do
     esac
 done
 
+# are we running under the unittests regime?
```
Comment (portante) [inline server/pbench/bin/pbench-report-status]: Can we put this logic into `unittests` instead?

File: server/pbench/bin/pbench-base.sh [hunk 2]
```diff
@@ -1,5 +1,8 @@
 #! /bin/bash
 
+# force UTC everywhere
+export TZ=UTC
```
Comment (portante) [inline server/pbench/bin/pbench-base.sh]: Did this change modify any gold files in and of itself?  If so, we should probably make this change as a separate commit.

File: server/pbench/bin/pbench-report-status [hunk 3]
```diff
@@ -21,8 +21,12 @@ while true; do
             shift 2
             ;;
         -t|--timestamp)
+            # timestamp is of the form run-<yyyy>-<mm>-<dd>T<HH>:<MM>:<SS>-<TZ>
+            # It's the variable TS created by pbench-base.sh.
+            # Snip off the initial "run-"
             timestamp="${2#run-}"
-            timestamp="${timestamp%-UTC}"
+            # Snip off the trailing "-<TZ>" - assumes that <TZ> does not contain a "-"
+            timestamp="${timestamp%-*}"
```
Comment (portante) [inline server/pbench/bin/pbench-report-status]: Are we sure we want to do this here?  It looks like `$timestamp` is used as a parameter to `pbench-gen-json-payload` where we want to make sure the payload's timestamp is in UTC.

So can we consider moving this stripping to line 89?

File: server/pbench/bin/pbench-report-status [hunk 4]
```diff
@@ -70,15 +84,12 @@ if [ ! -z "$report_using_mail" -a "$report_using_mail" != "no" ] ;then
     exit $status
 fi
 
-CONFIG=/opt/pbench-server/lib/config/pbench-index.cfg
-
-server=$(getconf.py server Server)
-datestamp=${timestamp%-*}
-index=$(getconf.py index_prefix Settings)."$name"."$datestamp"
+server=$(getconf.py --config $IDXCONFIG server Server)
```
Comment (portante) [inline server/pbench/bin/pbench-report-status]: Can we check that we get a server value?

File: server/pbench/bin/pbench-report-status [hunk 5]
```diff
@@ -70,15 +84,12 @@ if [ ! -z "$report_using_mail" -a "$report_using_mail" != "no" ] ;then
...
+# Snip off the time part of the timestamp
+datestamp=${timestamp%T*}
+index=$(getconf.py --config $IDXCONFIG index_prefix Settings)."$name"."$datestamp"
```
Comment (portante) [inline server/pbench/bin/pbench-report-status]: Before we build the index name, can we check that we get an index prefix?

File: server/pbench/bin/pbench-report-status [hunk 6]
```diff
@@ -70,15 +84,12 @@ if [ ! -z "$report_using_mail" -a "$report_using_mail" != "no" ] ;then
     exit $status
```
Comment (portante) [inline server/pbench/bin/pbench-report-status]: Can we put into the mail subject the timestamp value as well, something like, `$name status report at $timestamp`?

File: server/pbench/bin/pbench-base.sh (hunk 2 above)
Comment (ndokos) [reply server/pbench/bin/pbench-base.sh]: No, it was only affecting the results I was getting on my laptop (which is using local time).

Comment (portante) [reply server/pbench/bin/pbench-base.sh]: Probably worth making that a separate commit anyways.  That could save folks a lot of trouble and it would be good to have that exposed in the history.

Comment (ndokos) [reply server/pbench/bin/pbench-base.sh]: Split into a separate PR #910  which is a dependency for this PR. I'll rebase after #910 is merged.

File: server/pbench/bin/test-bin/curl [hunk 7]
```diff
@@ -0,0 +1,6 @@
+#! /bin/bash
+
+echo ${0##*/} $*
+
+file=${6#@}
+cat $file > $_testreportstatus
```
[the remark this answers is not in the document]
Comment (ndokos) [reply server/pbench/bin/test-bin/curl]: OK

File: server/pbench/bin/pbench-report-status (hunk 3 above)
Comment (ndokos) [reply server/pbench/bin/pbench-report-status]: OK

File: server/pbench/bin/pbench-report-status (hunk 4 above)
Comment (ndokos) [reply server/pbench/bin/pbench-report-status]: OK

File: server/pbench/bin/pbench-report-status (hunk 5 above)
Comment (ndokos) [reply server/pbench/bin/pbench-report-status]: OK

File: server/pbench/bin/pbench-report-status (hunk 6 above)
Comment (ndokos) [reply server/pbench/bin/pbench-report-status]: OK

**Comment by ndokos** [comment]
@portante: there is still unit test cruft in `pbench-base.sh` but the rest has been addressed. I've marked it `DO-NOT-MERGE` until I figure that out, but PTAL at what's there and let me know if there problems. Thanks!

**Comment by ndokos** [comment]
I had commented out the _reset_state call in the unittests scripts and forgot to uncomment it. I'll make sure to do that in the next iteration.

**Comment by ndokos** [comment]
@portante: PTAL - the timestamp functions for the unit tests are still in pbench-base.sh, but there is unit test cruft in lots of other scripts, so I'm giving up for now. If this looks OK, let's merge it and I'll open an issue for the rest of the cleanup.

**Comment by ndokos** [comment]
Despite the fact the checks passed, run_unittests failed with

    +++ Server Unit Tests +++
     ./server/pbench/bin/unittests: line 301: sed: command not found
    ./server/pbench/bin/unittests: line 301: sed: command not found
    --- Server Unit Tests ---
    The command "./run-unittests" exited with 0.

Investigating...

File: server/pbench/bin/unittests [hunk 8]
```diff
@@ -30,16 +36,24 @@ export _PBENCH_SERVER_TEST=1
...
+export IDXCONFIG=$_testopt/config/pbench-index.cfg
 export TMPDIR=$_testtmp
 export TZ="UTC"
 
 function _run {
     tname=$1
     shift
     echo "+++ Running $tname" >> $_testout
-    $_tdir/$tname $@ >> $_testout 2>&1
+    command -v $tname
```
Comment (portante) [inline server/pbench/bin/unittests]: Is this a necessary line?  It seems to emit the command to be executed before the test.  Should this go to `$_testout` or should we just remove it?

Comment (ndokos) [reply server/pbench/bin/unittests]: No, it was another debugging line that I forgot. I got rid of it, but I'm now looking at the sed failure. I'll update asap.

**Comment by ndokos** [comment]
@portante: PTAL - unit tests run (and pass) on Travis CI

**Comment by portante** [comment]
@tenstormavi, @chaitanyaenr, can one of you also review this PR?
